### ISSUE TITLE
Notification Center

### ISSUE THREAD

**Issue by Firemanjoe** [Kalvin126/BatteryNotifier#2]
I downloaded the latest version and I noticed that in my notification centre will not update the current percentage remaining on my iPhone.

**Comment by Kalvin126** [comment]
What is the difference in battery percentage? The percentage may be off by ~1-3% I have noticed which just may be due to how iOS determines percentage.

**Comment by Firemanjoe** [comment]
It actually corrected itself with 2 reboots and a reinstall of the software. I'm now wondering if my notification centre wasn't "stuck" because some of them were updating, and some weren't. But just to show, the percentage difference was showing to be approx. 60%... You can close this!
