### ISSUE TITLE
Feature Request — Display %

### ISSUE THREAD

**Issue by rei-vilo** [Kalvin126/BatteryNotifier#3]
Display battery percentage for each iDevice connected.

**Comment by Kalvin126** [comment]
Are you referring to %'s in the status bar menu? The notification menu already shows percentages.

**Comment by rei-vilo** [comment]
Not on the version I've downloaded. 

<img width="166" alt="capture 2016-04-04 a 19 28 21" src="https://cloud.githubusercontent.com/assets/951776/14256934/75c2edca-fa9b-11e5-9d4f-c4d71bd0ddf4.png">

**Comment by Kalvin126** [comment]
Sorry, I meant in the Notification Center. But would you prefer a percentage in the menu as well?

**Comment by rei-vilo** [comment]
Sorry, I wasn't specific enough. Yes, have the percentage on the menu as well would be nice. 

Does the synchronisation go through WiFi or BLE or both?

**Comment by Kalvin126** [comment]
Sure. Synchronization goes through USB or WiFi.

**Comment by Kalvin126** [comment]
Option to show device percentage in menu has been added in commit 7811e5d8872c7a8fdc83287ca02679898325af77

**Comment by rei-vilo** [comment]
Thank you so much!
