### ISSUE TITLE
get install appName, data using SDMMobileDevice

### ISSUE THREAD

**Issue by kapil0408** [Kalvin126/BatteryNotifier#5]
Thanks for this project. this is not an issue regarding your project.
Actually you used SDMMobileDevice project.

So do you have any idea to get install appName, data using SDMMobileDevice 

Please help me

Thanks

**Comment by Kalvin126** [comment]
There are domain key constants that are available to query in this file: https://github.com/samdmarshall/SDMMobileDevice/blob/e7daa697d7184860e91bbc867d20400a9f3c711b/Framework/MobileDevice/Services/Lockdown/SDMMD_Keys.h
See if anything there is of interest.

Again, this is not an issue revolving this project.

**Comment by kapil0408** [comment]
Ok, thanks for it.
